config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :posts do 
  resources :comments
 end
 resources :books do
  resources :chapters 
  
end   
resources :publishers
  root 'posts#index'
  get 'welcome/index'
  get 'welcome/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :chapters, dependent: :destroy
  has_many :book_publishers
  has_many :publishers, through: :book_publishers
   
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!

def index
  @books = Book.all
end

def show
 @book = Book.find(params[:id])

end

def new
  @book = current_user.books.build

 
end

def edit
 @book = Book.find(params[:id])
end
def destroy
@book = Book.find(params[:id])
@book.destroy
redirect_to books_path

 end

def create
 @book = current_user.books.build(book_params)

 if @book.save
redirect_to book_path(@book)
 else
    render 'new'
  end
end

def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
    redirect_to book_path(@book)
else
  render 'edit'
end
end


private
 def book_params

 params.require(:book).permit(:title, :description, :publisher_ids =>[])

end
end

app/views/books/_form.html.erb
<div class="col-md-5">
<%= form_for @book, :html => { :class => "form-horizontal book" } do |f| %>

  <% if @book.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div>
   
    <%#= f.collection_select(:publisher_ids, Publisher.order(:name), :id, :name,
                                 {multiple: true}) %> 
        <%=f.label :"publishers"%><br>                          
    <%= f.collection_select(:publisher_ids, Publisher.order(:name), :id, :name,
                                    {include_blank: true}, {multiple: true}) %>
  </div>                                                      
                                    

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn btn-default' %>
    </div>
  </div>
</div>
<% end %>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<div class="container">
<%- model_class = Book -%>
<div >
    <h1 class="text-center">BOOKS</h1>
       <div class="btn btn-primary float-right ml-2">
         <%= link_to "NEW BOOK",new_book_path,class:'btn btn-primary' %>
      </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:AuthorEmail) %></th>
     
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
    
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
         <td><%= book.user.email %></td>
        
        <td><%= book.title %></td>
        <td><%= book.description %></td>
      
        <td><%=l book.created_at %></td>
        <td>

 

 


         
            <%= link_to t('.Show', :default => t("helpers.links.show")),
                      book_path(book), :class => 'btn btn-primary' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_book_path(book), :class => 'btn btn-primary' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      book_path(book),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


</div>

app/views/books/new.html.erb
<%- model_class = @book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render :partial => 'form' %>

app/views/books/show.html.erb
<div class="row">
 <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="position-sticky pt-3">
      <div class="sidebar-header">
        <h3  class="chapter">Chapters</h3>
      </div>

      <% @book.chapters.each do  |chapter|%>
      <ul>
       <%= link_to book_chapter_path(@book, chapter),class:'text' do %>
        <hr>
        <li  class="text-center"> <%= chapter.title%></li>
        <% end %>
      </ul>
      <%end%>
  </div>
 </nav>  

<div class="col-md-10">
  <div class="border border-white">
    <%= link_to 'BACK', books_path,class:'btn btn-secondary'  %>            
    <%= link_to'EDIT', edit_book_path(@book),class:'btn btn-secondary' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            book_path(@book),
            :method => 'delete',
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
    <%= link_to t('Add chapter', :default => t("helpers.links.add chapter")),
              new_book_chapter_path(@book), :class => 'btn btn-primary'  %>
  </div>
  <hr>
    <div class="title border">
     <h1 class="c-title "><%=@book.title%></h1>
    </div>


    <div class="description">
     <p class="p-text"> <%=@book.description%></p>
    </div>

    <strong >Publishers of this book </strong>
    <% @book.book_publishers.each do |book_publisher| %>
    <li>
     <%= book_publisher.publisher.name %>
    </li>
    <% end%>
    
    
 </div>
</div>
  <%#=link_to 'show', book_chapter_path(@book, chapter),class:'btn btn-primary'%>
        
            <%#= link_to chapter.title, book_chapter_path(@book, chapter),class:'btn btn-default' %>  