config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :posts do 
  resources :comments
 end
 resources :books do
  resources :chapters 
  
end   
resources :publishers
  root 'posts#index'
  get 'welcome/index'
  get 'welcome/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :chapters, dependent: :destroy
  has_many :book_publishers
  has_many :publishers, through: :book_publishers
   
end

app/models/book_publisher.rb
class BookPublisher < ApplicationRecord
  belongs_to :book
  belongs_to :publisher

end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :comment, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
 has_many :comments,dependent: :destroy
   #has_many :users, through: :comments
  belongs_to :user
end
 

app/models/profile.rb
class Profile < ApplicationRecord
	#belongs_to :user
	validates :screenname, presence: true
	validates :city, presence: true
	validates :user_id, presence: true
	#has_many :comments, dependent: :destroy
end

app/models/publisher.rb
class Publisher < ApplicationRecord
 has_many :book_publishers
 has_many :books, through: :book_publishers

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments,dependent: :destroy
  has_many :posts ,dependent: :destroy
  has_many :books ,dependent: :destroy
end

app/controllers/.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
    @comments = Comment.where"profile_id =?",params[:id]
  end

  # GET /profiles/new
  def new
    @profile = current_user.build_profile
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
def create
 @profile = current_user.build_profile(profile_params)

 respond_to do |format|
  if @profile.save
    format.html { redirect_to @profile, notice: "Profile was successfully created." }
    format.json { render :show, status: :created, location: @profile }
  else
    format.html { render :new, status: :unprocessable_entity }
    format.json { render json: @profile.errors, status: :unprocessable_entity }
  end
end
end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:screenname, :city)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!

def index
  @books = Book.all
end

def show
 @book = Book.find(params[:id])

end

def new
  @book = current_user.books.build

 
end

def edit
 @book = Book.find(params[:id])
end
def destroy
@book = Book.find(params[:id])
@book.destroy
redirect_to books_path

 end

def create
 @book = current_user.books.build(book_params)

 if @book.save
redirect_to book_path(@book)
 else
    render 'new'
  end
end

def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
    redirect_to book_path(@book)
else
  render 'edit'
end
end


private
 def book_params

 params.require(:book).permit(:title, :description, :publisher_ids =>[])

end
end

app/controllers/chapters_controller.rb
class ChaptersController< ApplicationController
  before_action :find_book

 def new 
  @chapter = Chapter.new
 end

 def show
   @chapter = Chapter.find(params[:id])
 end


  

 def create
   @chapter = Chapter.new(chapter_params)
   @chapter.book_id = @book.id
   if @chapter.save
   	redirect_to book_path(@book)
  else
    render 'new' 
  end
end

 private
  def chapter_params
   params.require(:chapter).permit(:title, :body)
  end
  def find_book
    @book = Book.find(params[:book_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_action :authenticate_user!

def create
    @post = Post.find(params[:post_id])
    @comment= @post.comments.create(comment_params)
    #@comment= @post.comments.build(comment_params)
    @comment.user_id = current_user.id
   
   if @comment.save
      redirect_to @post
  else
    redirect_to @post, notice: "did not save!"
  end
end  



 def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end




private

 def comment_params
   #params.require(:comment).permit(:comment, :user_id)
   params.require(:comment).permit(:comment)
 end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  
  # GET /posts or /posts.json
  def index
    @post = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
     #binding.pry
    # byebug
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build #Post.new
    #@post = current_user.build_profile
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
     @post =  current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogwithcomment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header/header' %>
     <% if notice %>

       <%= render 'layouts/flash/flash'%>

     <%end%>


  <%= yield %>
 </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
   
  </body>
</html>

app/views/layouts/flash/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/header/_header.html.erb
<%#
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"  
      aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
<%# %>
<div class="banner">

<header>
    <img  class="logo" src="logo.png" >
       <nav>

        <ul class="nav-area">
          <li><a><%= link_to "HOME",root_path%></a></li>
          <li><a><%= link_to "BOOKS", books_path %></a></li>
          <li><a><%= link_to "Publishers", publishers_path %></a></li>
          <li><a> <%= link_to "Contact", welcome_contact_path %></a></li>
      
</ul>
</nav> 
        <ul>
        <%if  user_signed_in? %>
           <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn-area btn btn-danger"%>
        <%else%> 
          <%= link_to "Sign up", new_user_registration_path, class:"btn-area btn btn-primary"%>
          <%= link_to "Sign in", new_user_session_path, class:"btn-area btn btn-primary"%>
          <%end%>
        </ul>
    </header>

</div>

 

  