config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :posts do 
  resources :comments
 end
 resources :books do
  resources :chapters 
  
end   
resources :publishers
  root 'posts#index'
  get 'welcome/index'
  get 'welcome/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book 
end

app/controllers/chapters_controller.rb
class ChaptersController< ApplicationController
  before_action :find_book

 def new 
  @chapter = Chapter.new
 end

 def show
   @chapter = Chapter.find(params[:id])
 end


  

 def create
   @chapter = Chapter.new(chapter_params)
   @chapter.book_id = @book.id
   if @chapter.save
   	redirect_to book_path(@book)
  else
    render 'new' 
  end
end

 private
  def chapter_params
   params.require(:chapter).permit(:title, :body)
  end
  def find_book
    @book = Book.find(params[:book_id])
  end

end

app/views/chapters/_chapter.html.erb
<%= chapter.id %>
<div >  
<%= chapter.title %>
</div>
<div>
<%= chapter.body %>
</div>

app/views/chapters/new.html.erb
<div class="container">
 <%= form_with model: [@book, @book.chapters.build] do |form| %>

  <div class="field form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  <div>
 
  <div class="field form-group">
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>
 
  <p>
    <%= form.submit %>
  </p>
 <% end %>
</div>

app/views/chapters/show.html.erb
<div class="row">
   <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
      <div class="sidebar-header">
       <h3 class= "chapter">Chapters</h3>
      </div>
      <% @book.chapters.each do  |chapter|%>
      <ul>
       <%= link_to book_chapter_path(@book,chapter),class:'text' do %>
       <hr>
       <li class="text-center"> <%= chapter.title%></li>
       <% end %>
      </ul>
     <%end%>
    </div>
   </nav> 

 <div class="col-md-10">
   <div class="border border-white">
     <%= link_to 'BACK', books_path,class:'btn btn-secondary' %> 
   </div>
   <hr>
   <div class="title border">
    <h1 class="c-title "><%=@chapter.title%></h1>
   </div>
   <div class="description">
    <p class="p-text"> <%=@chapter.body%></p>
   </div>
</div>

 <%#=link_to 'show', book_chapter_path(@book, chapter),class:'btn btn-primary'%>
        
            <%#= link_to chapter.title, book_chapter_path(@book, chapter),class:'btn btn-default' %> 